# Generated by Django 5.2.7 on 2025-11-23 16:43

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('Published', django.db.models.manager.Manager()),
            ],
        ),
    ]
